# 📊 Day 14 — NumPy Basics (Practice Notebook)
### 100 Days of Data Science | by Shoaib Aslam

---

## Table of Contents

1️⃣ What is NumPy  
2️⃣ Why NumPy Matters  
3️⃣ Creating Arrays  
4️⃣ Array Properties  
5️⃣ Array Indexing & Slicing  
6️⃣ Array Operations  
7️⃣ Universal Functions (ufuncs)  
8️⃣ Reshaping & Flattening  
9️⃣ Statistical Operations on Wine Dataset  
🔟 When to Use What  

---
## 1️⃣ What is NumPy?

NumPy (Numerical Python) is the **foundation of data science in Python**.

It provides:
- Fast, memory-efficient arrays called **ndarrays**
- Mathematical and statistical functions
- The backbone for Pandas, Matplotlib, and Scikit-learn

> **Key idea:** NumPy arrays are faster than Python lists because they store data in contiguous memory blocks.

---
## 2️⃣ Why NumPy Matters?

| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Speed | Slow | Up to 50x faster |
| Memory | High | Low |
| Math operations | Manual loops | Vectorized (no loops) |
| Data types | Mixed | Fixed (homogeneous) |
| Used in ML | No | Yes — everywhere |

---
## 3️⃣ Creating Arrays

In [1]:
# Importing NumPy
import numpy as np
import pandas as pd

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [2]:
# 1D Array from a list
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

1D Array: [10 20 30 40 50]


In [3]:
# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Array of zeros
zeros = np.zeros((3, 3))
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Array of ones
ones = np.ones((2, 4))
print("Ones Array:\n", ones)

Ones Array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# Array with a range of values
range_arr = np.arange(0, 50, 5)
print("Range Array:", range_arr)

Range Array: [ 0  5 10 15 20 25 30 35 40 45]


In [7]:
# Array with evenly spaced values
linspace_arr = np.linspace(0, 1, 10)
print("Linspace Array:", linspace_arr)

Linspace Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [8]:
# Random integer array
random_arr = np.random.randint(1, 100, size=(3, 3))
print("Random Array:\n", random_arr)

Random Array:
 [[88 71 69]
 [61 92 67]
 [99 16 21]]


---
## 4️⃣ Array Properties

Every NumPy array has properties that describe its structure.

In [9]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Array:\n", arr)
print("Shape:", arr.shape)       # Rows x Columns
print("Dimensions:", arr.ndim)   # Number of dimensions
print("Size:", arr.size)         # Total number of elements
print("Data Type:", arr.dtype)   # Type of elements

Array:
 [[10 20 30]
 [40 50 60]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


#### 💡 Tip

| Property | Description | Example Output |
|----------|-------------|----------------|
| `.shape` | Rows x Columns | `(2, 3)` |
| `.ndim` | Number of dimensions | `2` |
| `.size` | Total elements | `6` |
| `.dtype` | Element data type | `int64` |

---
## 5️⃣ Array Indexing & Slicing

Accessing specific elements or portions of an array.

In [10]:
# 1D Indexing
arr1d = np.array([10, 20, 30, 40, 50])

print("First element:", arr1d[0])
print("Last element:", arr1d[-1])
print("Elements 1 to 3:", arr1d[1:4])

First element: 10
Last element: 50
Elements 1 to 3: [20 30 40]


In [11]:
# 2D Indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at row 0, col 1:", arr2d[0, 1])  # Output: 2
print("Element at row 2, col 2:", arr2d[2, 2])  # Output: 9
print("First row:", arr2d[0, :])
print("First column:", arr2d[:, 0])

Element at row 0, col 1: 2
Element at row 2, col 2: 9
First row: [1 2 3]
First column: [1 4 7]


In [12]:
# Boolean Indexing — filter elements by condition
arr = np.array([15, 25, 35, 45, 55, 65])

filtered = arr[arr > 40]
print("Elements greater than 40:", filtered)

Elements greater than 40: [45 55 65]


---
## 6️⃣ Array Operations

NumPy performs operations on entire arrays at once — no loops needed.

In [13]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [14]:
# Scalar operations — apply to every element
arr = np.array([10, 20, 30, 40, 50])

print("Add 5 to all:", arr + 5)
print("Multiply all by 2:", arr * 2)
print("Square all:", arr ** 2)

Add 5 to all: [15 25 35 45 55]
Multiply all by 2: [ 20  40  60  80 100]
Square all: [ 100  400  900 1600 2500]


In [15]:
# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

result = np.dot(mat1, mat2)
print("Matrix Multiplication:\n", result)

Matrix Multiplication:
 [[19 22]
 [43 50]]


---
## 7️⃣ Universal Functions (ufuncs)

ufuncs are fast built-in mathematical functions that work element-wise on arrays.

In [16]:
arr = np.array([1, 4, 9, 16, 25])

print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp([1, 2, 3]))
print("Log:", np.round(np.log(arr), 2))
print("Absolute:", np.abs([-5, -10, 15, -20]))

Square Root: [1. 2. 3. 4. 5.]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Log: [0.   1.39 2.2  2.77 3.22]
Absolute: [ 5 10 15 20]


In [17]:
# Trigonometric functions
angles = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(angles)

print("Sin:", np.round(np.sin(radians), 2))
print("Cos:", np.round(np.cos(radians), 2))

Sin: [0.   0.5  0.71 0.87 1.  ]
Cos: [1.   0.87 0.71 0.5  0.  ]


---
## 8️⃣ Reshaping & Flattening

Changing the shape of an array without changing its data.

In [18]:
# Reshape 1D to 2D
arr = np.arange(1, 13)
print("Original:", arr)

reshaped = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# Flatten 2D back to 1D
flat = reshaped.flatten()
print("Flattened:", flat)

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
# Transpose — swap rows and columns
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Original Shape:", arr2d.shape)

transposed = arr2d.T
print("Transposed Shape:", transposed.shape)
print("Transposed:\n", transposed)

Original Shape: (2, 3)
Transposed Shape: (3, 2)
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


---
## 9️⃣ Statistical Operations on Wine Dataset

Now applying NumPy on real data — the Winemag dataset.

In [22]:
# Load the dataset
df = pd.read_csv(r"C:\Users\aslam\Downloads\winemag-data-130k-v2.csv\winemag-data-130k-v2.csv", index_col=0)

# Extract points and price as NumPy arrays
points = df['points'].to_numpy()
price = df['price'].dropna().to_numpy()

print("Points Array Shape:", points.shape)
print("Price Array Shape:", price.shape)

Points Array Shape: (129971,)
Price Array Shape: (120975,)


In [23]:
# Basic statistics on Wine Points
print("--- Wine Points ---")
print("Mean:", np.mean(points))
print("Median:", np.median(points))
print("Std Dev:", np.round(np.std(points), 2))
print("Min:", np.min(points))
print("Max:", np.max(points))

--- Wine Points ---
Mean: 88.44713820775404
Median: 88.0
Std Dev: 3.04
Min: 80
Max: 100


In [24]:
# Basic statistics on Wine Price
print("--- Wine Price ---")
print("Mean:", np.round(np.mean(price), 2))
print("Median:", np.median(price))
print("Std Dev:", np.round(np.std(price), 2))
print("Min:", np.min(price))
print("Max:", np.max(price))

--- Wine Price ---
Mean: 35.36
Median: 25.0
Std Dev: 41.02
Min: 4.0
Max: 3300.0


In [25]:
# Percentiles of Wine Price
print("25th Percentile (Q1):", np.percentile(price, 25))
print("50th Percentile (Median):", np.percentile(price, 50))
print("75th Percentile (Q3):", np.percentile(price, 75))

25th Percentile (Q1): 17.0
50th Percentile (Median): 25.0
75th Percentile (Q3): 42.0


In [26]:
# Boolean Indexing — wines with points above 95
top_wines = points[points >= 95]
print("Wines scoring 95+:", len(top_wines))
print("Average score of top wines:", np.mean(top_wines))

Wines scoring 95+: 2416
Average score of top wines: 95.59561258278146


In [27]:
# Boolean Indexing — affordable wines under $20
affordable = price[price < 20]
print("Affordable wines (under $20):", len(affordable))
print("Average price of affordable wines: $", np.round(np.mean(affordable), 2))

Affordable wines (under $20): 39401
Average price of affordable wines: $ 14.2


In [28]:
# Normalize points to 0-1 scale (common in ML preprocessing)
points_normalized = (points - np.min(points)) / (np.max(points) - np.min(points))
print("Original Points Range:", np.min(points), "-", np.max(points))
print("Normalized Points Range:", np.round(np.min(points_normalized), 2), "-", np.round(np.max(points_normalized), 2))

Original Points Range: 80 - 100
Normalized Points Range: 0.0 - 1.0


#### What just happened? 🤔

Normalization scales all values between 0 and 1.  
This is used in machine learning so that no feature dominates just because of its scale.  
A wine with 80 points becomes 0.0 and a wine with 100 points becomes 1.0.

---
## 🔟 When to Use What

| Task | NumPy Function | Example |
|------|----------------|---------|
| Create array | `np.array()` | From list or nested list |
| Create zeros | `np.zeros()` | Initialize empty matrix |
| Create range | `np.arange()` | Sequence of numbers |
| Even spacing | `np.linspace()` | 10 values between 0 and 1 |
| Random values | `np.random.randint()` | Simulate data |
| Reshape | `.reshape()` | Change dimensions |
| Flatten | `.flatten()` | Convert 2D to 1D |
| Transpose | `.T` | Swap rows and columns |
| Statistics | `np.mean()`, `np.median()` | Summarize data |
| Math | `np.sqrt()`, `np.log()` | Element-wise calculations |
| Filter data | Boolean indexing | Get wines above 95 points |
| Normalize | Min-max formula | ML preprocessing |

---
## 🔑 Key Takeaways

→ NumPy arrays are faster and more memory-efficient than Python lists  
→ Always check `.shape`, `.ndim`, `.dtype` before working with a new array  
→ Boolean indexing lets you filter arrays without any loops  
→ NumPy operations work on entire arrays at once — no for loops needed  
→ Use `np.median()` over `np.mean()` when your data has outliers  
→ `reshape()` and `flatten()` are used heavily in machine learning pipelines  
→ Normalization is the first NumPy operation you will use in every ML project  
→ NumPy is the foundation — Pandas and Scikit-learn are built on top of it

---
## 📁 Connect & Follow the Journey

| Platform | Link |
|----------|------|
| 🐙 GitHub | https://github.com/imshoaibaslam/100-Days-of-Data-Science |
| 📊 Kaggle | https://www.kaggle.com/shoaib32922 |

---
*Day 14 of 100 — Keep Learning, Keep Building 🚀*